name: Build Windows EXE and Upload to Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up MSVCGW
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build exe with MinGW
        run: |
          cl /O2 /MD /Fe:home_pc_server.exe src\main.c src\network_utils.c ws2_32.lib iphlpapi.lib /link /SUBSYSTEM:WINDOWS /DEBUG:NONE
      - name: Upload exe to release
        uses: softprops/action-gh-release@v2
        with:
          files: home_pc_server.exe
          token: ${{ secrets.GITHUB_TOKEN }}
